### ISSUE TITLE
Choose a Creative Commons license

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#1]

**Comment by schams-net** [comment]
I suggest to use the same license as we use for the "TYPO3 CMS What's New Slides".

This **Creative Commons BY-NC-SA 3.0**, which means, you can use, copy, distribute, share, adapt the material for non-commercial purposes and as long as you credit the authors.

https://creativecommons.org/licenses/by-nc-sa/3.0/

**Comment by marble** [comment]
Or 4.0?
https://creativecommons.org/faq/#which-is-the-latest-version-of-the-licenses-offered-by-creative-commons

![grafik](https://user-images.githubusercontent.com/307057/39212406-f8250506-480e-11e8-9b51-a6b26ae4e2d9.png)

**Comment by schams-net** [comment]
I am happy with Attribution-NonCommercial-ShareAlike 4.0 International (**CC BY-NC-SA 4.0**), too.
