### ISSUE TITLE
"Directory and file structure" is outdated

### ISSUE THREAD

**Issue by WWidow** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#126]
The tutorial part "Directory and file structure" of "Extension Configuration" seems to be outdated:

Missing files and folders created in the steps before:
site_package/Configuration/TypoScript/Setup 
site_package/Configuration/TypoScript/Setup/Page.typoscript
site_package/Configuration/TypoScript/Setup/Part1FluidTemplateSection.typoscript
site_package/Configuration/TypoScript/Setup/Part2CssFileInclusion.typoscript
site_package/Configuration/TypoScript/Setup/Part4GlobalConfiguration.typoscript
site_package/Resources/Private/Partials/Page/Navigation
site_package/Resources/Private/Partials/Page/Navigation/MainNavigation.html
site_package/Resources/Public/Icons
site_package/Resources/Public/Icons/Extension.svg

Outdated files and folders:
site_package/ext_icon.png

**Comment by brotkrueml** [comment]
The folders and files are missing until v10 version of the documentation, since v11 they are described:
https://docs.typo3.org/m/typo3/tutorial-sitepackage/11.5/en-us/ExtensionConfiguration/Index.html#directory-and-file-structure

As v10 hits EOL in April, the docs for v10 are not adjusted anymore.
