### ISSUE TITLE
Code Snippet copy/paste not working properly

### ISSUE THREAD

**Issue by florinphp** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#138]
https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/FluidTemplates/Index.html

When trying to copy from the code snippet it's copying the line numbers also.
So when you paste it in the IDE you have to delete those character

In the image below:
- if you copy after selecting with the mouse;
- or you use the copy button
It will result in bringing  also the line numbers that are displayed ( numbers 1 to 13) to the text you're pasting in the the IDE

<img width="983" alt="image" src="https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage/assets/34255431/e83e7c38-16d3-42cf-ab91-0f524ecb970d">

I'm using:
- Chrome 115 
-  MacOS
- PHPStorm / Sublime Text

**Comment by brotkrueml** [comment]
This was already fixed some time ago, but the last rendering of the mentioned manual was before the fix date. I retriggered the rendering, now the line numbers are ignored when copying a snippet. Thanks for your report.

See: https://github.com/TYPO3-Documentation/sphinx_typo3_theme/issues/184

**Comment by florinphp** [comment]
Your welcomed @brotkrueml . I can confirm it's ok.
