### ISSUE TITLE
FluidTemplates page instructions

### ISSUE THREAD

**Issue by florinphp** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#139]
There are some mistakes / misleading information in the [Fluid Templates](https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/FluidTemplates/Index.html) page as follows:

1. At [The website layout file](https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/FluidTemplates/Index.html#the-website-layout-file) section it is mentioned the following:
`Move the <f:render partial="Navigation/MainNavigation.html" arguments="{_all}"/> part from file Resources/Private/Templates/Page/Default.html ...`
- when searching for  **<f:render partial="Navigation/MainNavigation.html" arguments="{_all}"/>**  there are entries that it should be in various files but not this one mentioned in the quoted text.
- it's mentioned wrongfully in the snipped [here](https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/FluidTemplates/Index.html#id8) where the snippet should include the navigation html portion.

2.  At [The page layout file](https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/FluidTemplates/Index.html#the-page-layout-file) it's mentioned _Open file site_package/Resources/Private/Templates/Page/Default.html_ and then it's discussed we should delete some lines. Then it's indicated, that we could use the Jumbotron snippet inside that file. But both the file path and name indicated in the snipped below it's different than the path indicated above it.
- site_package/Resources/Private/Templates/Page/Default.html
VS
EXT:site_package/Resources/Public/StaticTemplate/Step1Default.html

3. There are 3 files mentioned [Step1Default](https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/FluidTemplates/Index.html#id5).html, [Step2Default](https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/FluidTemplates/Index.html#id8).html, [Step3Default](https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/FluidTemplates/Index.html#id9).html with common text that changes on each. 
- I believe the author was pointing out to the same file, **Default.html** but different versions;
- this is very misleading for the reader, which will end up with 3 files created, just to realise that there should be just one.

4. At the end of this page, there are no indication on how to use what we've created.

**Comment by linawolf** [comment]
Hello @florinphp,

Thank you for your comment. I am sorry it took as such a long time to react. But we are few contributors and a large work load.

I agree that the section is in need of some overhaul. I know changed it while also switching to a bootstrap 5.3 template. Please check you issues are resolved with https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage/pull/177.

Greetings Lina - TYPO3 Documentation Team Leader
