### ISSUE TITLE
Add explanation / link for MenuProcessor

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#14]
In section https://docs.typo3.org/typo3cms/drafts/github/TYPO3-Documentation/SitePackageTutorial/MainMenuCreation/Index.html

it might be good to explain / add links to MenuProcessor and data processors in general. Especially because a lot of resources probably do not use this. 

What sometimes makes TYPO3 so confusing in my opinion are the various ways to do things and it is not always easy to determine at first glance what is the recommended way and which is the old way.

**Comment by schams-net** [comment]
I am against explaining the `MenuProcessor` as part of the Site Package Tutorial to be honest. I understand that some readers would possibly like to get more details when they read through the tutorial, but data processors deserve a more comprehensive and extensive documentation.

I am happy to add some links, but could not find any existing resources.

**Comment by sypets** [comment]
I think it makes sense to close this.
