### ISSUE TITLE
Summary has to be reworked

### ISSUE THREAD

**Issue by Alagts** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#179]
The current [summary ](https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/Summary/Index.html#summary) has to be reworked. Most of its content is obsolete or outdates or both. For example we don't install extensions in the extension manager anymore, but use composer instead.

### TYPO3 versions

main

**Comment by linawolf** [comment]
Resolved with https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage/pull/231
