### ISSUE TITLE
Installation of site-package

### ISSUE THREAD

**Issue by Hobokens** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#206]
### Current behavior

Right now there is the sentence: 

`In order to see a change in the TYPO3 backend or frontend your site package needs to be [installed](https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/ExtensionInstallation/Index.html#extension-installation).`

This sentence does not make it sufficiently clear to me that the installation of the site-package is necessary for the further steps in the tutorial.

### TYPO3 versions
TYPO3 13.4

### Link
https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/MinimalExample/Index.html

### Possible Solution

My suggested wording: To work with the site-package, it still needs to be installed.

`ddev composer req t3docs/site-package:@dev`

**Comment by linawolf** [comment]
Good idea, I made a PR
