### ISSUE TITLE
Copy the assets of the theme

### ISSUE THREAD

**Issue by Hobokens** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#207]
### Current behavior

In the tutorial it is suggested to use images, css etc. from the example site-package:

```
For the purpose of demonstration we created a theme based on Bootstrap and some custom CSS / JavaScript.

You can download the files of the example theme from https://github.com/TYPO3-Documentation/site_package/tree/main/Resources/Public

Now copy these files into folder Resources/Public of your site package.
```

After this step, however, the images etc. are not displayed in the frontend.
### Expected behavior/output

I expect all assets to be available in the front end.

### Links

https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/Assets/Index.html

### TYPO3 versions

13.4

### Possible Solution

Add
`ddev composer dump-autoload`

**Comment by linawolf** [comment]
Good point! As we did not have the assets folder before this step, the symlink in the assets folder did not yet get generated for you! I will add a paragraph about this
