### ISSUE TITLE
Create the backend page layouts

### ISSUE THREAD

**Issue by Hobokens** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#208]
### Current behavior

There is a wrong path for a backend layout
`
EXT:site_package/Configuration/TsConfig/Page/Default.tsconfig`

### TYPO3 versions

13.4

### Possible Solution

EXT:site_package/Configuration/TsConfig/Page/PageLayout/Default.tsconfig

**Comment by linawolf** [comment]
I cannot find any place where the wrong path is displayed. Where did you see that?

**Comment by Hobokens** [comment]
Das Tutorial wurde überarbeitet, sodass der Satz nicht mehr zu finden ist.

**Comment by linawolf** [comment]
Thanks for all your feedback, we are still working on improving this tutorial for TYPO3 13.4
