### ISSUE TITLE
The TYPO3 Fluid version

### ISSUE THREAD

**Issue by Hobokens** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#209]
### Current behavior

In the tutorial is written:

```
Replace file setup.typoscript of example minimal-extension-typoscript with the following lines:
packages/site-package/Configuration/Sets/Minimal/setup.typoscript

page = PAGE
page {
    10 = PAGEVIEW
    10 {
        paths {
            100 = EXT:site_package/Resources/Private/Templates/
        }
    }
}
```
(...)
```
Create a file named Default.html in folder packages/site-package/Resources/Private/Pages.
packages/site-package/Resources/Private/Pages/Default.html

Hello Fluid World!

Clear all caches and preview the web page.
```
I can't preview the web page. I get the error that `type = 0` is missing.

### Expected behavior/output

I can preview the web page in the browser.

### Links
https://docs.typo3.org/m/typo3/tutorial-sitepackage/main/en-us/MinimalExample/Index.html

### TYPO3 versions

13.4

**Comment by linawolf** [comment]
Have you added the site set to your site: https://docs.typo3.org/permalink/t3sitepackage:minimal-extension-siteset?

**Comment by Hobokens** [comment]
I don't remember whether I did this or not. I am therefore closing the issue.

**Comment by Hobokens** [comment]
I don't remember whether I did this or not. I am therefore closing the issue.
