### ISSUE TITLE
Embed youtube videos about sitepackage

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#23]
There are 2 videos about sitepackage

https://www.youtube.com/watch?v=HtBmim7pc0o
https://www.youtube.com/watch?v=deSMVfCSCXY

they should be embeded in the document somewhere.

Right now they are mentioned here, which is now easy to confuse this menu entry with the sitepackage tutorial:
https://docs.typo3.org/typo3cms/GuidesAndTutorials/Index.html#develop-a-site-package-extension

**Comment by schams-net** [comment]
I assume, we can close this ticket?  
The videos are embedded in [chapter Summary](https://docs.typo3.org/typo3cms/SitePackageTutorial/Summary/Index.html#videos-on-youtube), section "Videos on YouTube".

Quote:

> _In this three-parts series, Mathias Schreiber and Benjamin Kott set up a TYPO3 site from scratch by building a Site Package extension._

**Comment by tmotyl** [comment]
cool, thanks
