### ISSUE TITLE
Summary on https://docs.typo3.org/m/typo3/tutorial-sitepackage/13.4/en-us/ leads to 404

### ISSUE THREAD

**Issue by PKuhlmay** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#240]
Hi on page https://docs.typo3.org/m/typo3/tutorial-sitepackage/13.4/en-us/ there is a link "Summary", this leads to a 404 page

https://docs.typo3.org/m/typo3/tutorial-sitepackage/13.4/en-us/Summary/Index.html#summary

**Comment by linawolf** [comment]
It seems to work now, maybe the page was rendered in the moment that you tried?

**Comment by PKuhlmay** [comment]
The link works, but leads to the "Next Step" page. I expected to get to the Summary page, but I think it doesn't exist anymore? 
The better way would be, to rename the Link to "Next steps", instead of "Summary"?

Also the text "In this chapter we sum up the steps that we did after we have gone through this tutorial." seems to be wrong because there is nothing like that on the "Next steps" page.

**Comment by linawolf** [comment]
Yeah that is true, we removed the summary as it was never up to date to technology changes, the card needs to be changed

**Comment by PKuhlmay** [comment]
#254
