### ISSUE TITLE
Add markers to screenshots

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#3]
The tutorial refers to markers in the screenshots, but the no markers have been added yet.

**Comment by marble** [comment]
This is how this can be done:
 http://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html?highlight=text%20role#role-ref

1. Add a caption text to the figure
2. Place a label (like _ABC: in front of the figure)
3. Then use `:ref:`ABC` to create a link

**Comment by schams-net** [comment]
This is now what I meant by "markers in screenshots".  
I mean markers _in the image_, which point to a specific function or item:

![Markers in screenshots](https://user-images.githubusercontent.com/3617721/39393517-6ea0a5ee-4b09-11e8-8136-d3a3060103ff.png)

**Comment by marble** [comment]
Got it!
