### ISSUE TITLE
Add link to backend layouts page in TYPO3 explained

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Tutorial-SitePackage#40]
add to page:https://docs.typo3.org/m/typo3/tutorial-sitepackage/master/en-us/Summary/Index.html

First, backend layout documentation should be backported to older versions in "TYPO3 Explained". 

I will take care of this.

**Comment by linawolf** [comment]
The link is already there. Currently working on integrating examples, see #47
